name: Pipeline Workflow

on:
  push:
    branches:
      - dev-001-fiap
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-ci-pipeline-workflow:
    if: ${{ github.event_name == 'push' && github.ref == 'dev-001-fiap' }}
    uses: tshadz-fiap-postech-soat3/ci-pipeline/.github/workflows/ci-pipeline.yml@main
    secrets: inherit
