name: Pipeline Workflow

on:
  push:
    branches:
      - dev-001-fiap
  pull_request:
    branches:
      - main

jobs:
  call-ci-pipeline-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Test
        run: echo "testing"
