name: Pipeline Workflow

on:
  workflow_dispatch:

jobs:
  run_dast_scan:
    runs-on: ubuntu-latest

    env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fastfood
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          MYSQL_PORT: 3306
          MYSQL_HOST: db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Build and run Docker Compose
        run: docker-compose up --build -d

      - name: Check Docker container logs
        run: docker logs healthmed-doctor-api || true

      - name: Wait for services to be ready
        run: |
          docker-compose run --rm -T healthmed-doctor-api-db db:5432 -t 60
          docker-compose run --rm -T healthmed-doctor-api app:8080 -t 60

      - name: Test Container
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' healthmed-doctor-api)" == "true" ]; then
            curl -s http://localhost:8080 || exit 1
          else
            echo "Container is not running"
            exit 1
          fi

      - name: Check running containers
        run: docker ps

      - name: Inspect Network Configuration
        run: docker network inspect bridge

      - name: Run Zap Owasp Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'zaproxy/zap-stable'
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8080'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-reports/zap_report.html

      - name: Add ZAP Findings to Summary
        if: success()
        run: |
          echo '## OWASP ZAP Security Scan Results' >> $GITHUB_STEP_SUMMARY
          echo 'No Vulnerabilities detected ✅' >> $GITHUB_STEP_SUMMARY

      - name: Add ZAP Findings to Summary
        if: failure()
        run: |
          echo '## OWASP ZAP Security Scan Results' >> $GITHUB_STEP_SUMMARY
          echo 'Vulnerabilities detected ❌' >> $GITHUB_STEP_SUMMARY
          echo '<details>' >> $GITHUB_STEP_SUMMARY
          echo '<summary>ZAP HTML Report</summary>' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`html" >> $GITHUB_STEP_SUMMARY
          cat zap-reports/zap_report.html >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY

      - name: Stop and Remove Docker Container
        run: |
          docker stop myapp
          docker rm myapp
